### ISSUE TITLE
Speedup EMU for long cDNA reads

### ISSUE THREAD

**Issue by jodjo86** [treangenlab/emu#16]
In the minimap2 documentation, it is recommended to add the `-u f` argument for for long cDNA reads.  It is supposed to "speeds up alignment with slight improvement to accuracy". I haven't tested the accuracy but the speed is increased by 2-3x.

What do you think?

source: https://github.com/lh3/minimap2?tab=readme-ov-file#map-long-mrnacdna-reads

**Comment by kdc10** [comment]
Sounds good to me! Thanks for updating the code and submitting a PR!

**Comment by jodjo86** [comment]
Do you think it is possible to add the new version (3.4.6) to Bioconda?
