### ISSUE TITLE
errors with collapse-taxonomy

### ISSUE THREAD

**Issue by lucacozzuto** [treangenlab/emu#18]
Dear developers,
thanks for developing this tool! I was trying to collapse the taxonomy of one of my outputs and I got the following error:

```Traceback (most recent call last):
  File "/usr/local/bin/emu", line 880, in <module>
    collapse_rank(args.input_path, args.rank)
  File "/usr/local/bin/emu", line 636, in collapse_rank
    df_emu_copy = df_emu[['abundance', 'estimated counts'] + keep_ranks]
                  ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/frame.py", line 4108, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/usr/local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['genus', 'order', 'phylum', 'superkingdom'] not in index"
```

The input I have is like the following:

```
tax_id	abundance	lineage	estimated counts
1069	0.8936861989707546	Bacteria;Firmicutes;Bacilli;Lactobacillales;Lactobacillaceae;Lactobacillus;crispatus;	24116.122079225814
1827	0.003287748760082089	Bacteria;Firmicutes;Bacilli;Lactobacillales;Lactobacillaceae;Lactobacillus;	88.71990029081518
6305	0.004709765718838579	Bacteria;Firmicutes;Bacilli;Lactobacillales;Lactobacillaceae;Lactobacillus;iners;	127.09302792285906
7256	0.07553218381729783	Bacteria;Firmicutes;Bacilli;Lactobacillales;Streptococcaceae;Streptococcus;oralis;	2038.235980309782
```

Can you help me?

Thanks in advance,

Luca

**Comment by kdc10** [comment]
Hi,

In order to use collapse-taxonomy, the .tsv file must separate taxonomic ranks into different columns: ['species', 'genus', 'family', 'order', 'class', 'phylum', 'superkingdom']. You will need to first parse your file in preparation for this, to match the output structure of the default emu database.

**Comment by lucacozzuto** [comment]
Hi, thanks for this. So the parsing is not part of emu package? I got the database following the instructions from Silva using the tool indicated in the README. So only the emu db is properly formatted for this?

Thanks again

Luca

**Comment by lucacozzuto** [comment]
Hi again, I think I should have used the *taxonomy_split.tsv* file instead of *taxonomy.tsv* in the silva database for getting the results in the correct format. I think it would be nice to have the "split file" as the normal file and in the database (and maybe changing the name of unsplit one so that Emu can recognize correctly the right file.

Best,

Luca

**Comment by kdc10** [comment]
Ah yes, thanks for investigating this. I'd prefer to leave the Silva default as is to align with the structure of the provided Silva database. I also have not confirmed each Silva entry in the "split" database has the correct header, I simply split each Silva entry on the ";" delimiter. I will update the README to relay this information.
