### ISSUE TITLE
Problems with output file with unclassified sequences

### ISSUE THREAD

**Issue by ayamakawa** [treangenlab/emu#23]
Hi! 

I'm having problems when I run the "emu abundance" with the "--output-unclassified". This is the code I used and the resulting error:

`emu abundance FL005_16S23S_S01.fasta --db MIrROR_DB/ --output-basename FL005_16S23S_S01.fasta --threads 8 --output-unclassified --keep-files --keep-counts --keep-read-assignments --output-dir 16S23S_results/`

[M::mm_idx_gen::6.484*1.54] collected minimizers
[M::mm_idx_gen::7.096*2.02] sorted minimizers
[M::main::7.103*2.01] loaded/built the index for 97763 target sequence(s)
[M::mm_mapopt_update::7.140*2.01] mid_occ = 28998
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 97763
[M::mm_idx_stat::7.164*2.01] distinct minimizers: 1830421 (44.69% are singletons); average occurrences: 41.694; average spacing: 5.457; total length: 416474652
[M::worker_pipeline::876.227*7.93] mapped 7629 sequences
[M::worker_pipeline::878.959*7.93] mapped 28 sequences
[M::main] Version: 2.26-r1175
[M::main] CMD: minimap2 -ax map-ont -t 8 -N 50 -p .9 -K 500000000 -o 16S23S_results/FL005_16S23S_S01.fasta_emu_alignments.sam MIrROR_DB/species_taxid.fasta FL005_16S23S_m0_S01_noba.fasta FL005_16S23S_m1_S01_noba.fasta
[M::main] Real time: 879.049 sec; CPU: 6967.297 sec; Peak RSS: 7.290 GB
Unassigned read count: 1
Assigned read count: 7655
Number of EM iterations: 40
Traceback (most recent call last):
  File "/home/anayamakawa/miniconda3/envs/RESCUE_env/bin/emu", line 829, in <module>
    output_unclassified(SAM_FILE, "{}_unclassified".format(out_file), INPUT_FILETYPE)
  File "/home/anayamakawa/miniconda3/envs/RESCUE_env/bin/emu", line 94, in output_unclassified
    Seq(alignment.query_sequence),
  File "/home/anayamakawa/miniconda3/envs/RESCUE_env/lib/python3.7/site-packages/Bio/Seq.py", line 1728, in __init__
    "data should be a string, bytes, bytearray, Seq, or MutableSeq object"
TypeError: data should be a string, bytes, bytearray, Seq, or MutableSeq object

Even with this error, the alignments, assignments distributions and rel abundance files are produced. And if I remove the "--output-unclassified" it works without any error. 
Would you have any idea what could be the problem? 

Thank you!

**Comment by kdc10** [comment]
Interesting.  Could you tell me which version of emu you are running?

**Comment by ayamakawa** [comment]
I'm using the v3.4.5. I just saw that there's a new version. 
I will try update and see. I will let you know if worked!

Thank you!

**Comment by ayamakawa** [comment]
I update and try run again, but the error continues:

`emu abundance FL005_16S23S_m?_S01_noba.fasta --db MIrROR_DB/ --output-basename FL005_16S23S_S01.fasta --threads 8 --keep-files --keep-counts --output-unclassified --keep-read-assignments --output-dir 16S23S_results/`
[M::mm_idx_gen::6.460*1.51] collected minimizers
[M::mm_idx_gen::7.143*2.03] sorted minimizers
[M::main::7.151*2.03] loaded/built the index for 97763 target sequence(s)
[M::mm_mapopt_update::7.189*2.03] mid_occ = 28998
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 97763
[M::mm_idx_stat::7.211*2.02] distinct minimizers: 1830421 (44.69% are singletons); average occurrences: 41.694; average spacing: 5.457; total length: 416474652
[M::worker_pipeline::913.965*7.93] mapped 7629 sequences
[M::worker_pipeline::916.699*7.93] mapped 28 sequences
[M::main] Version: 2.26-r1175
[M::main] CMD: minimap2 -ax map-ont -t 8 -N 50 -p .9 -K 500000000 -o 16S23S_results/FL005_16S23S_S01.fasta_emu_alignments.sam MIrROR_DB/species_taxid.fasta FL005_16S23S_m0_S01_noba.fasta FL005_16S23S_m1_S01_noba.fasta
[M::main] Real time: 916.800 sec; CPU: 7269.797 sec; Peak RSS: 7.326 GB
Unassigned read count: 1
Assigned read count: 7655
Number of EM iterations: 40
Traceback (most recent call last):
  File "/home/anayamakawa/miniconda3/envs/RESCUE_env/bin/emu", line 839, in <module>
    output_unclassified(SAM_FILE, "{}_unclassified".format(out_file), INPUT_FILETYPE)
  File "/home/anayamakawa/miniconda3/envs/RESCUE_env/bin/emu", line 94, in output_unclassified
    Seq(alignment.query_sequence),
  File "/home/anayamakawa/miniconda3/envs/RESCUE_env/lib/python3.7/site-packages/Bio/Seq.py", line 1728, in __init__
    "data should be a string, bytes, bytearray, Seq, or MutableSeq object"
TypeError: data should be a string, bytes, bytearray, Seq, or MutableSeq object

Thank you for the assistance!

**Comment by kdc10** [comment]
I'm not sure what is causing this and I am unable to reproduce the error. Would you be willing to share your database and your fasta with me? Either here or to email: kristendcurry@gmail.com

**Comment by kdc10** [comment]
There was a sequence header without a corresponding sequence. Emu has been update to handle this: https://github.com/treangenlab/emu/releases/tag/v3.5.0
