### ISSUE TITLE
Taxonomy classification with different DB

### ISSUE THREAD

**Issue by ntromas** [treangenlab/emu#25]
Dear emu team,

I am currently using your pipeline to classify ONT fastq. I played a bit with the DB to compare emu-db and SILVA. I found several times, different results in term of number of classified taxa.
Here is an example of an output of the same sample:
from SILVA:
8903	0.3333333333333333	Bacteria;Planctomycetota;Phycisphaerae;Phycisphaerales;Phycisphaeraceae;SM1A02;	1.0
9107	0.3333333333333333	Bacteria;Proteobacteria;Alphaproteobacteria;Rhizobiales;Labraceae;Labrys;	1.0
285	0.3333333333333333	Bacteria;Actinobacteriota;Actinobacteria;Propionibacteriales;Nocardioidaceae;Nocardioides;	1.0

from EMU-db:
tax_id	abundance	species	genus	family	order	class	phylum	clade	superkingdom	subspecies	species subgroup	species group	estimated counts
443157	1.0	Nocardioides hankookensis	Nocardioides	Nocardioidaceae	Propionibacteriales	Actinobacteria	Actinobacteria	Terrabacteria group	Bacteria		3.0
unassigned	0.0

I can imagine that SILVA db is larger than emu-db and could identify more taxa but here I am not it would explain this.

Cheers,

Nico

**Comment by kdc10** [comment]
The SILVA database is larger and also less curated. You can use --keep-files to see the minimap2 alignments between your reads and the database
