### ISSUE TITLE
Min abundence question 

### ISSUE THREAD

**Issue by EsbergA** [treangenlab/emu#26]
Hi, I am currently using the Emu pipeline, and we have an issue with the --min-abundance command. 
The --min-abundance can be increased and then Emu generates an output file with the defined threshold. But it does not allow you to give a threshold below 0.0001, which is the default; this will give truncation of samples with a larger number of reads. Is there an option to get it all down to 1 mapped read or a defined 0.000001?
/ Anders

**Comment by kdc10** [comment]
You will have to go into the code and change the min abundance (line 302). We don't recommend doing this as we expect many false positives when lowering this threshold.
