### ISSUE TITLE
Combine-output 'species' issue

### ISSUE THREAD

**Issue by abbyf1120** [treangenlab/emu#27]
When I try to use the "emu combine-outputs --split-tables /mypath/ species" command, my tables are both empty. However, when I use "emu combine-outputs --split-tables /mypath/ tax_id," I will only obtain tables with the tax_id. 
I know that replacing tax_id with species is supposed to replace the IDs with their names, but I am not sure why these tables are blank. Do you have any advice?

**Comment by kdc10** [comment]
Which database did you use to generate the results? Is "species" in the header for your relative abundance results tables?

**Comment by abbyf1120** [comment]
> Which database did you use to generate the results? Is "species" in the header for your relative abundance results tables?

I realized the issue was with which database I choose. I am sorry about the confusion.
