### ISSUE TITLE
Custom database UNITE fungi update

### ISSUE THREAD

**Issue by moniwaldherr** [treangenlab/emu#3]
Hi,
we are currently using the UNITE general fasta v8.3 fungi pre-built database provided here and have been wondering whether there will be an update of it available in the near future?
Best,
Monika

**Comment by sunilnagpal** [comment]
We built this for our own project lately: https://osf.io/s59tn/?view_only=6defbb457eb84c11aa4ad30fee5ab0ae.  Trust this may be of some help.

Best,
Sunil

**Comment by moniwaldherr** [comment]
Thanks a lot for sharing, I just downloaded it and will try it in the near future.
Best,
Monika

**Comment by kdc10** [comment]
We do not intend on updating the emu pre-built UNITE databases, but we of course encouraging building databases with our `build-database` scripts and sharing as is done here! Thanks @sunilnagpal !
