### ISSUE TITLE
Segmentation fault - exit status 139 during minimap stage - v3.5.0

### ISSUE THREAD

**Issue by NickJD** [treangenlab/emu#31]
Hi,
I have a rare bug that seems to consistently happen to about 7 out of 60 or so ONT samples I have. I am using the default database with pretty much everything else set as default.

`emu abundance --threads 20 Lib3_barcode24_porechopped_all_chopped_q10_1250_1700.fastq.gz --db /xxx/Databases/Emu/default_emu/ --keep-counts  --keep-files  

[M::mm_idx_gen::1.002*1.25] collected minimizers
[M::mm_idx_gen::1.058*2.16] sorted minimizers
[M::main::1.061*2.16] loaded/built the index for 49243 target sequence(s)
[M::mm_mapopt_update::1.071*2.15] mid_occ = 14113
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 49243
[M::mm_idx_stat::1.078*2.14] distinct minimizers: 462637 (45.14% are singletons); average occurrences: 28.757; average spacing: 5.572; total length: 74133434
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/xxx/anaconda3/envs/emu_3.5.0/bin/emu", line 804, in <module>
    SAM_FILE = generate_alignments(args.input_file, out_file, args.db)
  File "/xxx/anaconda3/envs/emu_3.5.0/bin/emu", line 419, in generate_alignments
    shell=True)
  File "/xxx/anaconda3/envs/emu_3.5.0/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/xxx/anaconda3/envs/emu_3.5.0/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'minimap2 -ax map-ont -t 20 -N 50 -p .9 -K 500000000 /xxx/Databases/Emu/default_emu/species_taxid.fasta Lib3_barcode24_porechopped_all_chopped_q10_1250_1700.fastq.gz -o ./results/Lib3_barcode24_porechopped_all_chopped_q10_1250_1700.fastq_emu_alignments.sam' returned non-zero exit status 139.`

 
The bottom of the samfile looks like it is cutoff too.

`@SQ	SN:223919:emu_db:49161	LN:1512` 
`@SQ	SN:223919:emu_db:49162	LN:1514`  
`@SQ	SN:223919:emu_db`

Above is an example run and error for one of the failed samples. 
The other 50 or so samples work without issue.

I have checked the fastq files and everything looks fine.

Has anyone else had this issue?

I saw this issue which was similar but the version of minimap I have in my conda env is 2.28 https://gitlab.com/treangenlab/emu/-/issues/16

**Comment by NickJD** [comment]
A small update:
I have tested older versions of minimap2 back to v2.2 and emu back to v3.3.0 and I get basically the same error.
`[M::mm_idx_gen::1.006*1.24] collected minimizers
[M::mm_idx_gen::1.065*2.17] sorted minimizers
[M::main::1.069*2.17] loaded/built the index for 49243 target sequence(s)
[M::mm_mapopt_update::1.079*2.16] mid_occ = 14113
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 49243
[M::mm_idx_stat::1.086*2.15] distinct minimizers: 462637 (45.14% are singletons); average occurrences: 28.757; average spacing: 5.572; total length: 74133434
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/xxx/anaconda3/envs/emu_3.3.0/bin/emu", line 634, in <module>
    sam_file = generate_alignments(args.input_file, out_file, args.db)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/anaconda3/envs/emu_3.3.0/bin/emu", line 359, in generate_alignments
    subprocess.check_output(
  File "/xxx/anaconda3/envs/emu_3.3.0/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxx/anaconda3/envs/emu_3.3.0/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'minimap2 -ax map-ont -t 20 -N 50 -p .9 -K 500000000 /xxxx/Databases/Emu/default_emu/species_taxid.fasta Lib3_barcode24_porechopped_all_chopped_q10_1250_1700.fastq.gz -o new_results_3.3.0/Lib3_barcode24_porechopped_all_chopped_q10_1250_1700.fastq_emu_alignments.sam' returned non-zero exit status 139.`

However, whichever way I run this, it fails outputting the same line in the sam file (reported in the OP).
So I tried running emu on the raw ONT reads without running Chopper or PoreChop and I get the same error.

Each sample I have is a concatenation of multiple ONT output files for a specific barcode so I ran emu on one of the separate filed for a barcode that originally failed in the concatenated form and it does seem to work. It isn't this concatenation though as the vast majority of the other barcodes work fine.

Great tool otherwise :D

**Comment by kdc10** [comment]
You'll want to run emu on the concatenation of all files from the barcode. Running the files separately, then bringing the emu results together will likely produce a different result. 

`exit status 139` is often due to a memory problem. Are the 7 files that emu is crashing on bigger than the rest? Are you running this locally or on a remote server? Is there any way you could increase the memory allocation to this run? I'd recommend using the latest versions of minimap2 and emu.

**Comment by NickJD** [comment]
I see, I guess the model and classification is influenced by the set of reads it sees.

I am running this locally with 100GB of RAM and 80GB of swap. At no point do any of my emu runs use anywhere near that much and the 7 barcodes are no bigger or smaller than the others I have relatively.

I think it may be a problem with a specific read or barcode subfile but also it is really odd that they all fail writing out to the same place in the SAM file (shown in the OP).

Thanks

**Comment by kdc10** [comment]
If you send me one of the files that crash, I can try to look into it. kristendcurry@gmail.com

**Comment by NickJD** [comment]
Will close this issue as it seems to be a strange unknown problem with minimap2 on a Linux AMD based system.

Running 'just' the minimap command resulted in the same error so does not seem to be an issue with emu itself.

Thanks for debugging @kdc10
