### ISSUE TITLE
keep counts question

### ISSUE THREAD

**Issue by Thomieh73** [treangenlab/emu#5]
Hi, this morning I was reading over your instructions and then I noticed that the `keep counts` option outputs: Estimated counts". 

Could you explain what is happening with the abundances, when it is not real counts by estimated counts? Does that mean that you take the relative abundances and calculate back what the number of reads for a percentage is, for each sample?

**Comment by RadkaP** [comment]
If I may, this issue has been already answered by the author in ticket #42 on https://gitlab.com/treangenlab/emu/-/issues/42:

"Estimated counts is generated by simply multiplying the estimated abundance by the total number of mapped reads. "

**Comment by Thomieh73** [comment]
Thanks for answering.
