### ISSUE TITLE
Secondary alignments for short reads

### ISSUE THREAD

**Issue by TheDBStern** [treangenlab/emu#6]
Hello,

Great tool! I just wanted to bring to your attention something I learned recently: minimap2 does not report secondary alignments for short reads by default when using the `-x sr` preset, unless you set `--secondary=yes`. See https://github.com/lh3/minimap2/issues/846. I know Emu is designed primarily for long reads, but presumably this would impact the short read option.

-David

**Comment by kdc10** [comment]
Thanks for bringing this to our attention! Since `-N` is set to a value greater than 1 (default `50`), the `--secondary` flag should inherently be set to true. Please let us know if you are seeing otherwise in your results.
