### ISSUE TITLE
Question about LCA

### ISSUE THREAD

**Issue by Pstege** [treangenlab/emu#8]
Thank you very much for this nice tool! 
If I understand correctly, Emu does not apply a lowest common ancestor (LCA) like approach, right? This was not entirely clear for me when reading the paper. 

For instance, when Kraken2 cannot confidently assign a sequence to a species level, it will assign it to the lowest taxonomic rank possible, which is usually the genus level.

Cheers,
Paul

**Comment by kdc10** [comment]
Hi @Pstege,

Apologies for the delay. This is correct, Emu does not use LCA. Instead each read may be assigned multiple species with the likelihood percentage of each. These values are used directly when calculating the community profile, so a read is not forced to be classified as only a single species. To see a breakdown of this probability distribution for each read, you can use the `keep-read-assignments` flag.
